<?php
return ['messages'=>['About us'=>'About us','Author'=>'Author','Latest Workshops'=>'Latest Workshops','Lorem ipsum dolor sit amet, consectetur adipiscing elit.'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tempus nisl vitae magna pulvinar laoreet.'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tempus nisl vitae magna pulvinar laoreet.','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

Lorem ipsum dolor sit amet, consectetur adipiscing elit Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.','Our Team'=>'Our Team','Read more'=>'Read more','Testimonials'=>'Testimonials','View all'=>'View all','editor-text-editor-0c84079'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

Lorem ipsum dolor sit amet, consectetur adipiscing elit Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.','http://espaceconnect.acute.com/about-us/'=>'http://espaceconnect.acute.com/about-us/','http://espaceconnect.acute.com/trainers/'=>'http://espaceconnect.acute.com/trainers/','http://espaceconnect.acute.com/workshops/'=>'http://espaceconnect.acute.com/workshops/','occupation'=>'occupation','qi_addons_for_elementor_testimonials_slider-item_author-f96a5ae-b85689f'=>'Author','qi_addons_for_elementor_testimonials_slider-item_author-f96a5ae-f082de4'=>'Author','qi_addons_for_elementor_testimonials_slider-item_author-f96a5ae-ffbf11e'=>'Author','qi_addons_for_elementor_testimonials_slider-item_author_occupation-f96a5ae-b85689f'=>'occupation','qi_addons_for_elementor_testimonials_slider-item_author_occupation-f96a5ae-f082de4'=>'occupation','qi_addons_for_elementor_testimonials_slider-item_author_occupation-f96a5ae-ffbf11e'=>'occupation','qi_addons_for_elementor_testimonials_slider-item_text-f96a5ae-b85689f'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tempus nisl vitae magna pulvinar laoreet.','qi_addons_for_elementor_testimonials_slider-item_text-f96a5ae-f082de4'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tempus nisl vitae magna pulvinar laoreet.','qi_addons_for_elementor_testimonials_slider-item_text-f96a5ae-ffbf11e'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tempus nisl vitae magna pulvinar laoreet.','text-button-4888fb2'=>'Read more','text-button-b033138'=>'View all','text-button-f7f81c2'=>'View all','title-heading-3a145a4'=>'Our Team','title-heading-68c846c'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit','title-heading-a3bdcd5'=>'About us','title-heading-a81f7e4'=>'Latest Workshops','title-heading-fb80a36'=>'Testimonials','url-button-4888fb2'=>'http://espaceconnect.acute.com/about-us/','url-button-b033138'=>'http://espaceconnect.acute.com/workshops/','url-button-f7f81c2'=>'http://espaceconnect.acute.com/trainers/']];
